---
name: MvpMovie
options:
  bundleIdPrefix: com.mvpmovie.app
  transitivelyLinkDependencies: true
  deploymentTarget:
    iOS: 14.0
settings:
  base:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
    CODE_SIGN_STYLE: Automatic
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    GCC_OPTIMIZATION_LEVEL: 0
    SWIFT_COMPILATION_MODE: singlefile
    SWIFT_OPTIMIZATION_LEVEL: -Onone
    TARGETED_DEVICE_FAMILY: 1
  configs:
    release:
      GCC_OPTIMIZATION_LEVEL: s
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: Configs/Debug.xcconfig
  Release: Configs/Release.xcconfig
include:
    - Clients/HttpClient/HttpClient.yml
    - Features/Features.yml
packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    version: 5.6.2
  Swinject:
    url: https://github.com/Swinject/Swinject.git
    version: 2.8.2
  SwinjectAutoregistration:
    url: https://github.com/Swinject/SwinjectAutoregistration.git
    version: 2.8.1
targets:
  Mock:
    type: application
    platform: iOS
    templates: 
      - MvpMovie
    sources:
      - path: MvpMovie/Configurations/Mock
        createIntermediateGroups: true
  Development:
    type: application
    platform: iOS
    templates: 
      - MvpMovie
    sources:
      - path: MvpMovie/Configurations/Live
        createIntermediateGroups: true
    dependencies:
      - target: HttpClientLive
      - package: Alamofire
  Production:
    type: application
    platform: iOS
    templates: 
      - MvpMovie
    sources:
      - path: MvpMovie/Configurations/Live
        createIntermediateGroups: true
    dependencies:
      - target: HttpClientLive
      - package: Alamofire
targetTemplates:
  MvpMovie:
    type: application
    platform: iOS
    sources:
      - path: MvpMovie/Common
        createIntermediateGroups: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mvpmovie.app
    dependencies:
      - target: HttpClient
      - target: Features
      - package: Swinject
      - package: SwinjectAutoregistration
    prebuildScripts:
      - name: CodeFormatting
        path: "scripts/pre_build_code_formatting.sh"
schemes:
  Mock:
    build:
      targets:
        Mock: all
    run:
      config: Debug
    archive:
      config: Debug
    test:
      config: Debug
  Development:
    build:
      targets:
        Development: all
    run:
      config: Debug
    archive:
      config: Debug
    test:
      config: Debug
  Production:
    build:
      targets:
        Production: all
      config: Release
    archive:
      config: Release
